fault_type = ('Faults Cleared', 'Init Fault', 'Init Fault - Mfg', 'Axis Fault', 'Axis Fault - Mfg', 'Motion Fault', 'Module Fault', 'Group Fault', 'Configuration Fault', 'APR Fault', 'APR Fault - Mfg', 'Safety Fault', 'Safety Fault - Mfg', 'Reserved', 'Guard Fault', 'Vendor Specific')

fault_code_001 = ('Reserved', 'Boot Block Checksum ', 'Main Block Checksum ', 'Nonvolatile Memory Checksum ', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved')

fault_code_002 = ('Reserved', 'Feedback Data Corruption ', 'Feedback Data Range ', 'Feedback Communication Startup', 'Feedback Absolute Overspeed ', 'Feedback Abs Power Off Travel', 'Feedback Abs Startup Speed ', 'Commutation Offset Uninit', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Invalid FPGA Image ', 'Invalid Board Support Package ', 'Invalid Safety Firmware ', 'Power Board ', 'Illegal Option Card ', 'Option Storage Checksum ', 'Reserved', 'Module Voltage Mismatch', 'Unknown Module ', 'Factory Configuration Error ', 'Illegal Address ', 'Series Mismatch ', 'Open Slot ', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved')

fault_code_003 = ('Reserved', 'Motor Overcurrent', 'Motor Commutation ', 'Motor Overspeed FL ', 'Motor Overspeed UL ', 'Motor Overtemperature FL ', 'Motor Overtemperature UL ', 'Motor Thermal Overload FL ', 'Motor Thermal Overload UL ', 'Motor Phase Loss', 'Inverter Overcurrent ', 'Inverter Overtemperature FL ', 'Motor Overtemperature UL ', 'Inverter Thermal Overload FL ', 'Inverter Thermal Overload UL ', 'Converter Overcurrent ', 'Converter Ground Current FL ', 'Converter Ground Current UL ', 'Converter Overtemperature FL ', 'Converter Overtemperature UL ', 'Converter Thermal Overload FL ', 'Converter Thermal Overload UL ', 'Converter AC Power Loss ', 'Converter AC Single Phase Loss', 'Converter AC Phase Short ', 'Converter Pre-Charge ', 'Reserved', 'Bus Regulator Overtemp FL ', 'Bus Regulator Overtemp UL ', 'Bus Reg Thermal Overload FL ', 'Bus Reg Thermal Overload UL ', 'Bus Regulator Failure', 'Bus Capacitor Module Failure', 'Bus Undervoltage FL ', 'Bus Undervoltage UL ', 'Bus Overvoltage FL ', 'Bus Overvoltage UL ', 'Bus Power Loss ', 'Bus Power Blown Fuse ', 'Bus Power Leakage ', 'Bus Power Sharing ', 'Feedback Signal Noise FL ', 'Feedback Signal Noise UL ', 'Feedback Signal Loss FL ', 'Feedback Signal Loss UL ', 'Feedback Data Loss FL ', 'Feedback Data Loss UL ', 'Feedback Device ', 'Reserved', 'Brake Slip', 'Hardware Overtravel Positive ', 'Hardware Overtravel Negative ', 'Position Overtravel Positive ', 'Position Overtravel Negative ', 'Excessive Position Error ', 'Excessive Velocity Error ', 'Overtorque Limit ', 'Undertorque Limit ', 'Reserved', 'Reserved', 'Illegal Control Mode ', 'Enable Input Deactivated ', 'Controller Initiated Exception', 'External Input Exception')

fault_code_004 = ('Reserved', 'Commutation Startup Failure', 'Motor Voltage Mismatch', 'Reserved', 'Feedback Filter Noise ', 'Feedback Battery Loss ', 'Feedback Battery Low ', 'Fdback Incremental Count Error', 'Reserved', 'Reserved', 'Control Module Overtemp FL ', 'Control Module Overtemp UL ', 'Converter PreCharge OL FL', 'Converter PreCharge OL UL', 'Excessive Current Fdbck Offset', 'Regenerative Power Supply ', 'PWM Frequency Reduced ', 'Current Limit Reduced ', 'Torque Prove Failure', 'Decel Override ', 'Preventative Maintenance ', 'Motor Test Failure', 'Hardware Configuration ', 'Firmware Change ', 'Cnverter PreCharge Inp. Deact', 'DC Common Bus ', 'Runtime Error ', 'Backplane Comm Error  ', 'Safety Module Comm Error ', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Product Specific ')

fault_code_005 = ('Reserved', 'Soft OT - Positive', 'Soft OT - Negative', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved')

fault_code_006 = ('Control Sync ', 'Module Sync ', 'Timer Event ', 'Module Hard ', 'Reserved', 'Reserved', 'Module Conn ', 'Conn Format ', 'Local Mode ', 'CPU Watchdog ', 'Clock Jitter ', 'Cyclic Read ', 'Cyclic Write ', 'Clock Skew ', 'Control Conn ', 'Reserved', 'Clock Sync ', 'Logic Watchdog ', 'Duplicate Address ', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved')

fault_code_007 = ('Group Overlap', 'CST Loss', 'Group Task Loading', 'Clock Sync ', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved')

fault_code_008 = ('Success', 'Connection Failure', 'Resource Unavailable', 'Invalid value in obj specific ', 'IOI segment error', 'IOI destination unknown', 'Partial Transfer', 'Connection lost', 'Unimplemented service', 'Invalid attribute value', 'Attribute list error', 'Already in requested mode/stat', 'Object cannot perform service ', 'Object already exists', 'Attribute value not settable', 'Access permission does not all', 'Device$s mode/state does not a', 'Reply Data too large', 'Fragmentation of a primitive v', 'Not enough data', 'Undefined attribute', 'Too much data', 'Object does not exist', 'Service fragmentation sequence', 'No stored attribute data', 'Store operation failure', 'Bridging failure, request pack', 'Bridging failure, response pac', 'Missing attribute list entry d', 'Invalid attribute value list', 'Embedded service error', 'Connection Related Failure', 'Invalid Parameter', 'Write-once value or medium alr', 'Invalid Reply Received', 'CST not coordinated', 'Connection Scheduling Error', 'Key Failure in IOI', 'IOI Size Invalid', 'Unexpected attribute in list', 'DNet Invalid Member ID', 'DNet Member not settable', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved')

fault_code_009 = ('Reserved', 'Memory Write Error', 'Memory Read Error', 'Fdback Serial Number Mismatch', 'Buffer Allocation ', 'Scaling Configuration Changed', 'Feedback Mode Changed', 'Feedback Integrity Loss', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved')

fault_code_010 = ('Reserved', 'Persistent Media ', 'Firmware Error', 'Fdback Battery Loss', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved')

fault_code_011 = ('Reserved', 'Safety Core', 'Safety Feedback', 'Safe Torque Off', 'SS1', 'SS2', 'SOS', 'SBC', 'SMT', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'SSM', 'SLS', 'SLA', 'SDI', 'SCA', 'SLP', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Safety Validator', 'Reserved')

fault_code_012 = ('Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved')

fault_code_128 = ('Reserved', 'Guard Internal ', 'Guard Configuration ', 'Guard Gate Drive ', 'Guard Reset ', 'Guard Feedback 1 ', 'Guard Feedback 2 ', 'Guard Feedback Speed Compare ', 'Guard Feedback Pos Compare ', 'Guard Stop Input ', 'Guard Stop Output ', 'Guard Stop Decel ', 'Guard Stop Standstill ', 'Guard Stop Motion ', 'Guard Limited Speed Input ', 'Guard Limited Speed Output ', 'Guard Limited Speed Monitor ', 'Guard Max Speed Monitor ', 'Guard Max Accel Monitor ', 'Guard Direction Monitor ', 'Guard Door Monitor Input ', 'Guard Door Monitor ', 'Guard Door Control Output ', 'Guard Lock Monitor Input ', 'Guard Lock Monitor ', 'Guard Enable Sw Monitor Inp ', 'Guard Enabling Switch Monitor ', 'Guard Fdback 1 Voltage Monitor', 'Guard Fdback 2 Voltage Monitor', 'Reserved (RLM Reset Fault)', 'Reserved', 'Reserved')

fault_type_zero_message = ('No Faults', 'Module Reset', 'Fault Reset', 'Shutdown Reset', 'Connection Reset', 'Fault Log Reset')

stop_action = ('No Action', 'Planner Stop', 'Ramped Stop', 'Torque Limited Stop', 'ImmediateStop(Coast)')

state_change = ('No Action', 'Hold', 'Disable', 'Shutdown')

alarm_type = ('No Alarms', 'Start Inhibit', 'Start Inhibit - Mfg', 'Axis Alarm', 'Axis Alarm - Mfg', 'Motion Alarm', 'Module Alarm', 'Group Alarm', 'Remote Get Alarm')

alarm_code_001 = ('Reserved', 'Axis Enable Input Inhibit', 'Motor Not Configured Inhibit', 'Fdback Not Configured Inhibit', 'Commutation Not Config Inhibit', 'Safe Torque Off Active Inhibit', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved')

alarm_code_002 = ('Reserved', 'Volts Hertz Curve Def Inhibit', 'Motor Fdback Required Inhibit', 'Speed Limit Config Inhibit', 'Torque Prove Configuration Inh', 'Safe Torque Off Inhibit', 'Safety Reset Required Inhibit', 'Safety Not Configured Inhibit', 'Stop Command Active Inhibit', 'Feedback Device Reset Inhibit', 'Brake Malfunction Inhibit', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved')

alarm_code_003 = ('Reserved', 'Motor Overcurrent', 'Motor Commutation ', 'Motor Overspeed FL ', 'Motor Overspeed UL ', 'Motor Overtemperature FL ', 'Motor Overtemperature UL ', 'Motor Thermal Overload FL ', 'Motor Thermal Overload UL ', 'Motor Phase Loss', 'Inverter Overcurrent ', 'Inverter Overtemperature FL ', 'Motor Overtemperature UL ', 'Inverter Thermal Overload FL ', 'Inverter Thermal Overload UL ', 'Converter Overcurrent ', 'Converter Ground Current FL ', 'Converter Ground Current UL ', 'Converter Overtemperature FL ', 'Converter Overtemperature UL ', 'Converter Thermal Overload FL ', 'Converter Thermal Overload UL ', 'Converter AC Power Loss ', 'Converter AC Single Phase Loss', 'Converter AC Phase Short ', 'Converter Pre-Charge ', 'Reserved', 'Bus Regulator Overtemp FL', 'Bus Regulator Overtemp UL', 'Bus Reg Thermal Overload FL', 'Bus Reg Thermal Overload UL ', 'Bus Regulator Failure', 'Bus Capacitor Module Failure', 'Bus Undervoltage FL ', 'Bus Undervoltage UL ', 'Bus Overvoltage FL ', 'Bus Overvoltage UL ', 'Bus Power Loss ', 'Bus Power Blown Fuse ', 'Bus Power Leakage ', 'Bus Power Sharing ', 'Feedback Signal Noise FL ', 'Feedback Signal Noise UL ', 'Feedback Signal Loss FL ', 'Feedback Signal Loss UL ', 'Feedback Data Loss FL ', 'Feedback Data Loss UL ', 'Feedback Device ', 'Reserved', 'Brake Slip', 'Hardware Overtravel Positive ', 'Hardware Overtravel Negative ', 'Position Overtravel Positive ', 'Position Overtravel Negative ', 'Excessive Position Error ', 'Excessive Velocity Error ', 'Overtorque Limit ', 'Undertorque Limit ', 'Reserved', 'Reserved', 'Illegal Control Mode ', 'Enable Input Deactivated ', 'Controller Initiated Exception', 'External Input Exception')

alarm_code_004 = ('Reserved', 'Commutation Startup', 'Motor Voltage Mismatch', 'Reserved', 'Feedback Filter Noise ', 'Feedback Battery Loss ', 'Feedback Battery Low ', 'Fdback Inc Count Error', 'Reserved', 'Reserved', 'Control Module Overtemp FL ', 'Control Module Overtemp UL ', 'Cnverter PreCharge Overload FL', 'Cnverter PreCharge Overload UL', 'Excessive Current Fdbck Offset', 'Regenerative Power Supply ', 'PWM Frequency Reduced ', 'Current Limit Reduced ', 'Torque Prove Failure', 'Decel Override ', 'Preventative Maintenance ', 'Motor Test Failure', 'Hardware Configuration ', 'Firmware Change ', 'Cnvrter PreCharge Inp Deact', 'DC Common Bus ', 'Runtime Error ', 'Backplane Comm Error  ', 'Safety Module Comm Error ', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Product Specific ')

alarm_code_005 = ('Reserved', 'Soft OT - Positive', 'Soft OT - Negative', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved')

alarm_code_006 = ('Control Sync ', 'Module Sync ', 'Timer Event ', 'Processor Overload', 'Clock Jitter ', 'Out of Range', 'Clock Skew ', 'Clock Sync ', 'Node Address', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved')

alarm_code_007 = ('Clock Sync', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved', 'Reserved')

alarm_type_zero_messages = ('Alarm Log Reset')

undefined = ('Undefined')

alarm_or_fault = ('None', 'Alarm', 'Fault', 'Reset')

alarm_action = ('Alarm Off', 'Alarm On')
